paths:
  base_dir: "YOUR_PATH_HERE/AcademicAgent-Suite"
  raw_storage: "YOUR_PATH_HERE/AcademicAgent-Suite/storage/raw"
  processed_storage: "YOUR_PATH_HERE/AcademicAgent-Suite/storage/processed"

environments:
  doc_recognize: "YOUR_PATH_HERE/AcademicAgent-Suite/envs/DocRecognize/bin/python"
  video_recognize: "YOUR_PATH_HERE/AcademicAgent-Suite/envs/VideoRecognize/bin/python"
  visual_inference: "YOUR_PATH_HERE/AcademicAgent-Suite/envs/VisualInference/bin/python"
  sandbox_inference: "YOUR_PATH_HERE/AcademicAgent-Suite/envs/SandboxInference/bin/python"
  data_stream: "YOUR_PATH_HERE/AcademicAgent-Suite/envs/DataStream/bin/python"
  agent_logic: "YOUR_PATH_HERE/AcademicAgent-Suite/envs/AgentLogic/bin/python"
  
model_paths:
  whisper: "YOUR_PATH_HERE/AcademicAgent-Suite/models/whisper_v3"
  qwen2_vl: "YOUR_PATH_HERE/AcademicAgent-Suite/models/qwen2_vl"
  miner_u: "YOUR_PATH_HERE/AcademicAgent-Suite/models/miner_u"
  clip: "YOUR_PATH_HERE/AcademicAgent-Suite/models/clip"
  dinov2: "YOUR_PATH_HERE/AcademicAgent-Suite/models/dinov2/"
  
database:
  milvus_host: "localhost"
  milvus_port: "19530"
  redis_host: "localhost"
  redis_port: "6379"